version: "3.9"
services:
  mqtt_broker:
    container_name: huebot_mqtt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /usr/local/bin/mosquitto/huebot.conf:/mosquitto/config/conf.d/huebot.conf
      - /usr/local/bin/mosquitto/data:/mosquitto/data
      - /usr/local/bin/mosquitto/log:/mosquitto/log
      - /usr/local/bin/config.json:/etc/mosquitto/huebot.config
    ports:
      - 18831:1883
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork

