version: "3.9"
services:
  mqtt_broker:
    container_name: huebot_mqtt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
    volumes:
      - /usr/local/bin/mosquitto/data:/mosquitto/data
      - /usr/local/bin/mosquitto/log:/mosquitto/log
    ports:
      - 18831:1883
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork

